// import 'package:flutter/cupertino.dart';
// import 'package:flutter/material.dart';
// import 'package:font_awesome_flutter/font_awesome_flutter.dart';

// class IconMap {
//   static Map<int, Icon> _iconMap = {
//     1: Icon(Icons.home_repair_service, color: Colors.red),
//     2: Icon(FontAwesomeIcons.eye, size: 18, color: Colors.blue),
//     3: Icon(FontAwesomeIcons.hotel, size: 18, color: Colors.blue.shade800),
//     4: Icon(FontAwesomeIcons.carAlt, size: 18, color: Colors.blueGrey),
//     5: Icon(FontAwesomeIcons.mugHot, size: 18, color: Colors.red.shade600),
//     6: Icon(FontAwesomeIcons.soundcloud, size: 18, color: Colors.green),
//     7: Icon(FontAwesomeIcons.shoppingBag, size: 18, color: Colors.yellow),
//     8: Icon(FontAwesomeIcons.shoppingBasket,
//         size: 18, color: Colors.lightGreen),
//     9: Icon(FontAwesomeIcons.userMd, size: 18, color: Colors.teal),
//     10: Icon(FontAwesomeIcons.truckLoading, size: 18, color: Colors.amber),
//     11: Icon(FontAwesomeIcons.utensils, size: 18, color: Colors.brown),
//     12: Icon(FontAwesomeIcons.breadSlice,
//         size: 18, color: Colors.amber.shade300),
//     13: Icon(FontAwesomeIcons.calendarWeek, size: 18, color: Colors.lightBlue),
//     14: Icon(FontAwesomeIcons.dollarSign, size: 18, color: Colors.purple),
//     15: Icon(FontAwesomeIcons.handsHelping, size: 18, color: Colors.pink),
//     16: Icon(FontAwesomeIcons.wrench, size: 18, color: Colors.cyan),
//     17: Icon(FontAwesomeIcons.placeOfWorship, size: 18, color: Colors.brown),
//     18: Icon(FontAwesomeIcons.pills, size: 18, color: Colors.blueGrey),
//     19: Icon(FontAwesomeIcons.cog, size: 18, color: Colors.tealAccent),
//     20: Icon(FontAwesomeIcons.handHoldingUsd,
//         size: 18, color: Colors.purpleAccent),
//     21: Icon(FontAwesomeIcons.handHoldingMedical,
//         size: 18, color: Colors.greenAccent),
//     22: Icon(FontAwesomeIcons.industry, size: 18, color: Colors.black),
//     23: Icon(FontAwesomeIcons.userTie, size: 18, color: Colors.black),
//     24: Icon(FontAwesomeIcons.baby, size: 18, color: Colors.black),
//     25: Icon(FontAwesomeIcons.key, size: 18, color: Colors.black),
//     26: Icon(FontAwesomeIcons.users, size: 18, color: Colors.black),
//     27: Icon(FontAwesomeIcons.shoppingBag, size: 18, color: Colors.black),
//     28: Icon(FontAwesomeIcons.landmark, size: 18, color: Colors.black),
//     29: Icon(FontAwesomeIcons.video, size: 18, color: Colors.black),
//     30: Icon(FontAwesomeIcons.bed, size: 18, color: Colors.black),
//     31: Icon(FontAwesomeIcons.lungs, size: 18, color: Colors.black),
//     32: Icon(FontAwesomeIcons.virus, size: 18, color: Colors.black),
//     33: Icon(FontAwesomeIcons.beer, size: 18, color: Colors.black),
//     34: Icon(FontAwesomeIcons.male, size: 18, color: Colors.black),
//     35: Icon(FontAwesomeIcons.warehouse, size: 18, color: Colors.black),
//     36: Icon(FontAwesomeIcons.birthdayCake, size: 18, color: Colors.black),
//     37: Icon(FontAwesomeIcons.female, size: 18, color: Colors.black),
//     // 38: Icon(FontAwesomeIcons.washer, size: 18, color: Colors.black),
//     39: Icon(FontAwesomeIcons.book, size: 18, color: Colors.black),
//     40: Icon(FontAwesomeIcons.microscope, size: 18, color: Colors.black),
//     41: Icon(FontAwesomeIcons.wifi, size: 18, color: Colors.black),
//     42: Icon(FontAwesomeIcons.building, size: 18, color: Colors.black),
//     43: Icon(FontAwesomeIcons.mobileAlt, size: 18, color: Colors.black),
//     44: Icon(FontAwesomeIcons.xRay, size: 18, color: Colors.black),
//     // 45: Icon(FontAwesomeIcons.burgerSoda, size: 18, color: Colors.black),
//     46: Icon(FontAwesomeIcons.motorcycle, size: 18, color: Colors.black),
//     47: Icon(FontAwesomeIcons.babyCarriage, size: 18, color: Colors.black),
//     48: Icon(FontAwesomeIcons.bus, size: 18, color: Colors.black),
//     49: Icon(FontAwesomeIcons.paw, size: 18, color: Colors.black),
//     50: Icon(FontAwesomeIcons.hotel, size: 18, color: Colors.black),
//     // 51: Icon(FontAwesomeIcons.cameraAlt, size: 18, color: Colors.black),
//     // 52: Icon(FontAwesomeIcons.phoneLaptop, size: 18, color: Colors.black),
//     53: Icon(FontAwesomeIcons.mapMarkerAlt, size: 18, color: Colors.black),
//     54: Icon(FontAwesomeIcons.car, size: 18, color: Colors.black),
//     55: Icon(FontAwesomeIcons.pizzaSlice, size: 18, color: Colors.black),
//     56: Icon(FontAwesomeIcons.shoppingBag, size: 18, color: Colors.black),
//     // 57: Icon(FontAwesomeIcons.carMechanic, size: 18, color: Colors.black),
//     58: Icon(FontAwesomeIcons.planeDeparture, size: 18, color: Colors.black),
//     // 59: Icon(FontAwesomeIcons.airConditioner, size: 18, color: Colors.black),
//     // 60: Icon(FontAwesomeIcons.cars, size: 18, color: Colors.black),
//     // 61: Icon(FontAwesomeIcons.popcorn, size: 18, color: Colors.black),
//     // 62: Icon(FontAwesomeIcons.analytics, size: 18, color: Colors.black),
//     63: Icon(FontAwesomeIcons.cartArrowDown, size: 18, color: Colors.black),
//     // 64: Icon(FontAwesomeIcons.ringWedding, size: 18, color: Colors.black),
//     // 65: Icon(FontAwesomeIcons.userHardHat, size: 18, color: Colors.black),
//     // 66: Icon(FontAwesomeIcons.cctv, size: 18, color: Colors.black),
//     67: Icon(FontAwesomeIcons.school, size: 18, color: Colors.black),
//     68: Icon(FontAwesomeIcons.hammer, size: 18, color: Colors.black),
//     69: Icon(FontAwesomeIcons.child, size: 18, color: Colors.black),
//     70: Icon(FontAwesomeIcons.shippingFast, size: 18, color: Colors.black),
//     // 71: Icon(FontAwesomeIcons.utensilsAlt, size: 18, color: Colors.black),
//     72: Icon(FontAwesomeIcons.clinicMedical, size: 18, color: Colors.black),
//     73: Icon(FontAwesomeIcons.shopify, size: 18, color: Colors.black),
//     74: Icon(FontAwesomeIcons.broom, size: 18, color: Colors.black),
//     75: Icon(FontAwesomeIcons.cocktail, size: 18, color: Colors.black),
//     76: Icon(FontAwesomeIcons.shoppingCart, size: 18, color: Colors.black),
//     77: Icon(FontAwesomeIcons.plug, size: 18, color: Colors.black),
//     78: Icon(FontAwesomeIcons.coffee, size: 18, color: Colors.black),
//     79: Icon(FontAwesomeIcons.solarPanel, size: 18, color: Colors.black),
//     // 80: Icon(FontAwesomeIcons.flowerTulip, size: 18, color: Colors.black),
//     // 81: Icon(FontAwesomeIcons.construction, size: 18, color: Colors.black),
//     82: Icon(FontAwesomeIcons.stethoscope, size: 18, color: Colors.black),
//     83: Icon(FontAwesomeIcons.couch, size: 18, color: Colors.black),
//     84: Icon(FontAwesomeIcons.desktop, size: 18, color: Colors.black),
//     85: Icon(FontAwesomeIcons.store, size: 18, color: Colors.black),
//     86: Icon(FontAwesomeIcons.chalkboardTeacher, size: 18, color: Colors.black),
//     87: Icon(FontAwesomeIcons.diagnoses, size: 18, color: Colors.black),
//     88: Icon(FontAwesomeIcons.subway, size: 18, color: Colors.black),
//     89: Icon(FontAwesomeIcons.userGraduate, size: 18, color: Colors.black),
//     90: Icon(FontAwesomeIcons.dog, size: 18, color: Colors.black),
//     91: Icon(FontAwesomeIcons.syringe, size: 18, color: Colors.black),
//     // 92: Icon(FontAwesomeIcons.sunGlasses, size: 18, color: Colors.black),
//     93: Icon(FontAwesomeIcons.dumbbell, size: 18, color: Colors.black),
//     94: Icon(FontAwesomeIcons.tachometerAlt, size: 18, color: Colors.black),
//     95: Icon(FontAwesomeIcons.paintRoller, size: 18, color: Colors.black),
//     // 96: Icon(FontAwesomeIcons.faucetDrip, size: 18, color: Colors.black),
//     97: Icon(FontAwesomeIcons.tag, size: 18, color: Colors.black),
//     // 98: Icon(FontAwesomeIcons.vacuum, size: 18, color: Colors.black),
//     99: Icon(FontAwesomeIcons.fireExtinguisher, size: 18, color: Colors.black),
//     100: Icon(FontAwesomeIcons.taxi, size: 18, color: Colors.black),
//     // 101: Icon(FontAwesomeIcons.refrigerator, size: 18, color: Colors.black),
//     // 102: Icon(FontAwesomeIcons.garageCar, size: 18, color: Colors.black),
//     103: Icon(FontAwesomeIcons.tools, size: 18, color: Colors.black),
//     104: Icon(FontAwesomeIcons.gasPump, size: 18, color: Colors.black),
//     105: Icon(FontAwesomeIcons.tooth, size: 18, color: Colors.black),
//     106: Icon(FontAwesomeIcons.gifts, size: 18, color: Colors.black),
//     107: Icon(FontAwesomeIcons.train, size: 18, color: Colors.black),
//     108: Icon(FontAwesomeIcons.glassCheers, size: 18, color: Colors.black),
//     // 109: Icon(FontAwesomeIcons.transporter, size: 18, color: Colors.black),
//     // 110: Icon(FontAwesomeIcons.guitars, size: 18, color: Colors.black),
//     111: Icon(FontAwesomeIcons.truckMoving, size: 18, color: Colors.black),
//     112: Icon(FontAwesomeIcons.handshake, size: 18, color: Colors.black),
//     113: Icon(FontAwesomeIcons.tshirt, size: 18, color: Colors.black),
//     114: Icon(FontAwesomeIcons.heartbeat, size: 18, color: Colors.black),
//     115: Icon(FontAwesomeIcons.tv, size: 18, color: Colors.black),
//     116: Icon(FontAwesomeIcons.headSideMask, size: 18, color: Colors.black),
//     117: Icon(FontAwesomeIcons.university, size: 18, color: Colors.black),
//     118: Icon(FontAwesomeIcons.hospitalUser, size: 18, color: Colors.black),
//     119: Icon(FontAwesomeIcons.userMd, size: 18, color: Colors.black),
//     // 120: Icon(FontAwesomeIcons.houseDay, size: 18, color: Colors.black),
//     121: Icon(FontAwesomeIcons.userCog, size: 18, color: Colors.black),
//     122: Icon(FontAwesomeIcons.iceCream, size: 18, color: Colors.black),
//     123: Icon(FontAwesomeIcons.userFriends, size: 18, color: Colors.black),
//   };
//   static Icon? iconById(int? id) => _iconMap[id!];

//   static Icon copyColor(Icon icon, {required Color color}) => Icon(
//         icon.icon,
//         color: color,
//         size: icon.size,
//       );
// }
